version: '3'
services:
     es-master:
       image:  elasticsearch:6.5.4
       container_name: es-master
       restart: always
       volumes:
         - ./conf/es.yml:/usr/share/elasticsearch/config/elasticsearch.yml
       ports:
         - "9200:9200"
         - "9300:9300"

     es-node1:
       image:  elasticsearch:6.5.4
       container_name: es-node1
       restart: always
       volumes:
         - ./conf/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
       ports:
         - "9201:9201"
         - "9301:9301"
     es-node2:
       image:  elasticsearch:6.5.4
       container_name: es-node2
       restart: always
       volumes:
         - ./conf/es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
       ports:
         - "9202:9202"
         - "9302:9302"
     es-head:
       image: tobias74/elasticsearch-head:6
       container_name: es-head
       restart: always
       ports:
       - "9100:9100"